name: retry
on:
  workflow_dispatch:
jobs:
  check-previous-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: check previous build
        gh api \
        -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
         /repos/SARALAGOVIND/MY-GITHUBPROJECT/actions/workflows/${{github.run_id}}/runs
