name: 1020B_Load_Usage_TX
on: 
  workflow_dispatch:
  workflow_call:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
   
    - name: reuse1
      run: echo "iam 1021_Load_Monitor_TX"
