name: concurrency_Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: run the script
        run: echo "hi"
      - name: Dispatch Job Request
        uses: peter-evans/repository-dispatch@v1
        with:
          token: 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
          repository: Saralagovind/my-githubproject
          event-type: job-request
