name: job1
on:
  workflow_dispatch:
  
jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: step1
        run: echo "hi"
      - name: workflow status
        id: status
        run: echo "::set-output name=status::failure"
      
