name: job2
on:
  workflow_run:
    workflows: ["job1"]
    types:
      - completed
  
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: job2
        run: echo "hi"
