name: job2
on:
  workflow_dispatch:
  workflow_call:
jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: job2
        run: echo "hi"
