name: job3
on:
  workflow_run:
    workflows: ["job1"]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: job3
        run: echo "hi"
