name: rebuild
on:
  workflow_dispatch:
jobs:
  check-previous-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      #  continue-on-error: true
#       - name: to check the previous run
#         if: ${{ github.event.workflow_run.conclusion == 'success' }}
      - name: check previous build
        run: |
           curl -L -X POST  https://api.github.com/repos/Saralagovind/my-githubproject/actions/runs/${{github.run_id}}/rerun -H "Accept: application/vnd.github+json" -H "Authorization: Bearer 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" -H "X-GitHub-Api-Version: 2022-11-28"
#         -H "Accept: application/vnd.github+json" 
#         -H "X-GitHub-Api-Version: 2022-11-28" \
#          /repos/SARALAGOVIND/MY-GITHUBPROJECT/actions/workflows/${{github.run_id}}/runs
