name: rebuild
on:
  workflow_dispatch:
jobs:
  check-previous-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      #  continue-on-error: true
#       - name: to check the previous run
#         if: ${{ github.event.workflow_run.conclusion == 'success' }}
      - name: check previous build
        run: |
           curl -L \
           -X POST \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer 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"\
           -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Saralagovind/my-githubproject/actions/runs/${{github.run_id}}/rerun
#         #gh api \
#         -H "Accept: application/vnd.github+json" 
#         -H "X-GitHub-Api-Version: 2022-11-28" \
#          /repos/SARALAGOVIND/MY-GITHUBPROJECT/actions/workflows/${{github.run_id}}/runs
