name: retrigger
on:
  workflow_run:
   workflows: [retrigger]
   types:
    - completed
   result: failure
   
jobs:
  rerun:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: echo "hi"
    - name: step2
      run: sdf
      
