name: reusable workflow
on:
  workflow_dispatch:
  workflow_call:
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
 
    - name: reuse
      run: echo " iam reused one"
