name: my workflow
on:
  workflow_dispatch:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: checkout code
       uses: actions/checkout@v2
     - name: hello
       run: echo "sarala"
     - name: run reusable workflow
       uses: workflows@main
    
