name: Schedule Failed Builds

on:
  workflow_dispatch:
#   schedule:
#     - cron: '0 0 * * *'  # Schedule runs at midnight every day

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run build
        run: echo "hi"
      - name: failed
        uses: nick-fields/retry@v2
        with:
         timeout_minutes: 10
         max_attempts: 3
         command: echo "hello"

      
