name: throttle_concurrence
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v2
     - name: Create lock
       run: |
        touch lock.txt
     - name: Check lock
       id: check_lock
       run: |
         if [ -f lock.txt ]; then
         echo "::set-output name=lock::true"
         else
         echo "::set-output name=lock::false"
         fi
     - name: Exit if locked
       run: |
         if [[ "${{ steps.check_lock.outputs.lock }}" == "true" ]]; then
         echo "Job is already running. Exiting..."
         exit 0
         fi
     - name: Remove lock
       run: |
        rm -f lock.txt



     - name: run the script
       run: echo " hi"
     - name: Release lock
       run: rm -f .lock

       
       
        
