name: TestConcurrency
concurrency: <1>
#       group: my-concurrency
#       cancel-in-progress: false
on:  
  workflow_dispatch:
jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - run : echo "Hello"
