name: workflow_3
on:
  workflow_run:
    workflows: ["workflow_1"]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: executing script
        run: echo "job1 is failed so job3 executing "
