name: workflow_2
on:
  workflow_run:
    workflows: ["workflow_1"]
    types: [completed]
      
  
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: job2
        run: echo "job1 is failed so job2 is executing "
